name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t nadeem9748/nodejs-app  .
      - name: Publish Image to docker hub
        run: docker push nadeem9748/nodejs-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull nadeem9748/nodejs-app:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}'-e PORT='${{ secrets.PORT }}'-e MONGO_URI='${{ secrets.MONGO_URI }}'-e JWT_SECRET_CODE='${{ secrets.JWT_SECRET_CODE }}'-e BUCKET_NAME='${{ secrets.BUCKET_NAME }}'-e BUCKET_REGION='${{ secrets.BUCKET_REGION }}'-e ACCESS_KEY='${{ secrets.ACCESS_KEY }}'-e SECRET_ACCESS_KEY='${{ secrets.SECRET_ACCESS_KEY }}'-e CLOUD_FRONT_DIST_ID='${{ secrets.CLOUD_FRONT_DIST_ID }}'-e GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}'-e GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' -e GOOGLE_GENAI_API_KEY='${{ secrets.GOOGLE_GENAI_API_KEY }}' nadeem9748/nodejs-app